import process from "node:process";

export const IS_PRODUCTION = process.env.NODE_ENV === "production";
export const IS_ON_LOCAL = process.env.ENV === "local";
export const PORT = process.env.PORT ?? 5173;
export const BASE = process.env.BASE ?? "/";

export const CONSOLE_COLORS = {
  reset: "\x1b[0m",
  bright: "\x1b[1m",
  dim: "\x1b[2m",
  underscore: "\x1b[4m",
  blink: "\x1b[5m",
  reverse: "\x1b[7m",
  hidden: "\x1b[8m",
  fg_black: "\x1b[30m",
  fg_red: "\x1b[31m",
  fg_green: "\x1b[32m",
  fg_yellow: "\x1b[33m",
  fg_blue: "\x1b[34m",
  fg_magenta: "\x1b[35m",
  fg_cyan: "\x1b[36m",
  fg_white: "\x1b[37m",
  bg_black: "\x1b[40m",
  bg_red: "\x1b[41m",
  bg_green: "\x1b[42m",
  bg_yellow: "\x1b[43m",
  bg_blue: "\x1b[44m",
  bg_magenta: "\x1b[45m",
  bg_cyan: "\x1b[46m",
  bg_white: "\x1b[47m",
};

export const RESTRICTED_USERNAMES = {
  genericNames: [
    "user",
    "username",
    "password",
    "email",
    "name",
    "surname",
    "phone",
    "address",
    "city",
    "country",
    "zip",
    "postal",
    "code",
    "state",
    "province",
    "region",
    "dob",
    "date",
    "birth",
    "webmail",
    "gmail",
    "yahoo",
    "support",
    "helpdesk",
    "info",
    "contact",
    "contactus",
    "contact-us",
    "contact_us",
    "contact-me",
    "contact_me",
    "contactme",
    "about",
    "aboutus",
    "about-us",
    "about_us",
    "about-me",
    "about_me",
    "aboutme",
    "terms",
    "termsandconditions",
    "blog",
    "news",
    "newsroom",
    "press",
    "pressroom",
    "media",
    "mediaroom",
    "careers",
    "jobs",
    "job",
    "work",
    "workwithus",
    "work-with-us",
    "work_with_us",
    "work-withus",
    "shop",
    "store",
    "products",
    "services",
    "pricing",
    "plans",
    "pricingplans",
    "pricing-plans",
    "pricing_plans",
    "dashboard",
    "panel",
    "controlpanel",
    "control-panel",
    "control_panel",
    "adminpanel",
    "admin-panel",
    "admin_panel",
    "api",
    "cdn",
    "assets",
    "static",
    "images",
    "img",
    "photos",
    "pictures",
    "videos",
    "vids",
    "inbox",
    "outbox",
    "proxy",
    "vpn",
    "ssh",
    "sftp",
    "telnet",
    "http",
    "https",
  ],

  serverReservedNames: [
    "server",
    "servers",
    "server1",
    "server2",
    "server3",
    "server4",
    "server5",
    "server6",
    "localhost",
    "www",
    "tcp",
    "ftp",
    "smtp",
    "pop",
    "imap",
    "mail",
    "admin",
    "administrator",
    "root",
    "dns",
    "ssl",
    "tls",
    "oauth",
    "sso",
  ],

  knownBrandNames: [
    "google",
    "facebook",
    "twitter",
    "instagram",
    "linkedin",
    "youtube",
    "whatsapp",
    "snapchat",
    "tiktok",
    "telegram",
    "pinterest",
    "tumblr",
    "reddit",
    "github",
    "gitlab",
    "bitbucket",
    "microsoft",
    "apple",
    "amazon",
    "netflix",
    "spotify",
    "paypal",
    "ebay",
    "aliexpress",
    "alibaba",
  ],

  knownBrandNamesEndings: [
    "inc",
    "llc",
    "corp",
    "co",
    "com",
    "org",
    "net",
    "io",
    "dev",
    "tech",
    "app",
    "edu",
    "gov",
    "mil",
  ],

  reservedSubdomains: [
    "www",
    "partner",
    "partners",
    "admin",
    "administrator",
    "root",
    "support",
    "help",
    "helpdesk",
    "premium",
    "premiums",
    "premiumsupport",
    "premium-support",
    "premium_support",
    "premiumhelp",
    "vip",
    "vips",
    "vipsupport",
    "vip-support",
    "vip_support",
    "viphelp",
    "billing",
    "payments",
    "business",
    "enterprise",
    "corporate",
    "company",
    "companies",
    "businesses",
    "enterprises",
    "gallery",
    "media",
    "news",
    "blog",
    "blogs",
    "press",
    "pressroom",
    "newsroom",
    "media",
    "weddings",
    "events",
    "event",
    "eventplanner",
    "event-planner",
    "event_planner",
    "eventplanning",
    "clients",
    "customers",
    "users",
    "members",
    "subscribers",
    "partners",
    "affiliates",
    "resellers",
    "api",
    "pro",
    "studio",
  ],
};
